# 应用服务 WEB 访问端口
server:
  port: 8008
spring:
  redis:
    host: 192.168.121.130
    port: 6379
  zipkin:
    discovery-client-enabled: false
    base-url: http://192.168.121.130:9411/
    sender:
      type: web
  sleuth:
    sampler:
      rate: 1

oauth2:
  weibo:
    client-id: 2012499535
    client-secret: c7fe2f3a3268f84f16ba41a064167a1f
    grant-type: authorization_code


seata:
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 192.168.121.130:8848
      group: DEFAULT_GROUP
      username: nacos
      password: nacos
      namespace: ""
  tx-service-group: mall-seata
  service:
    vgroup-mapping:
      mall-seata: SH