# 应用服务 WEB 访问端口
server:
  port: 8009
spring:
  redis:
    host: 192.168.121.130
    port: 6379
  session:
    store-type: redis
  zipkin:
    discovery-client-enabled: false
    base-url: http://192.168.121.130:9411/
    sender:
      type: web
  sleuth:
    sampler:
      rate: 1

mall:
  thread:
    core-pool-size: 10
    keep-alive-time: 1000
    maximum-pool-size: 50


seata:
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 192.168.121.130:8848
      group: DEFAULT_GROUP
      username: nacos
      password: nacos
      namespace: ""
  tx-service-group: mall-seata
  service:
    vgroup-mapping:
      mall-seata: SH
